# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Orderer 노드를 관리하는 Org 정의
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: kukkiwon.com
    # ---------------------------------------------------------------------------
    # "Specs" - 전체 설명은 아래 Peer Org를 참조하십시오.
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
# ---------------------------------------------------------------------------
# "PeerOrgs" - Peer 노드를 관리하는 'Org' 정의
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.kukkiwon.com
    EnableNodeOUs: true #client와 peer의 식별
    # ---------------------------------------------------------------------------
    # "Specs"
    # ---------------------------------------------------------------------------
    # configuration에서 호스트의 명시적인 정의를 사용하려면 이 절의 주석을 제거하십시오.
    # 대부분의 사용자들은 아래의 템플릿을 사용합니다.
    #
    # 각 Spec 항목은 두 개의 필드로 구성 :
    #   - Hostname:   (필수) 원하는 호스트 이름은 도메인을 제외합니다.
    #   - CommonName: (선택 사항) CommonName에 대한 템플릿 또는 명시적으로 지정합니다.  
    #
    #     기본적으론 다음의 템플릿을 사용합니다.
    #                    "{{.Hostname}}.{{.Domain}}"
    #
    #                 Spec.Hostname 및 Org.Domain에서 해당 값을 각각 가져옵니다.
    # ---------------------------------------------------------------------------
    # Specs:
    #   - Hostname: nds # 암묵적으로 "nds.org1.kukkiwon.com"
    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    # Template에서 순차적으로 작성되는 하나 이상의 호스트를 정의 할 수 있습니다. 
    # 기본적으로이 값은 0에서 Count-1까지의 "peer %d"와 같습니다.
    # 노드 수 (Count), 시작 인덱스 (Start) 또는 이름을 구성하는 데 사용 된 템플릿 (Hostname)을 
    # 무시할 수 있습니다.
    #
    # 주의 : 템플리트 및 스펙은 상호 배타적이지 않습니다.  
    # 두 섹션을 모두 정의하면 집계 노드가 자동으로 생성됩니다. 이름 충돌에주의하십시오.
    # ---------------------------------------------------------------------------
    Template:
      Count: 2 #peer의 개수
      # Start: 5
      # Hostname: {{.Prefix}}{{.Index}} # default
    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: 사용자 계정 수-추가_관리자 수
    # ---------------------------------------------------------------------------
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Org2: 전체 설명은 Org1을 참고하십시오.
  # ---------------------------------------------------------------------------
  - Name: Org2 #이름
    Domain: org2.kukkiwon.com #도메인
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
